# Generated by Django 4.0.3 on 2022-03-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
