# Generated by Django 4.0.3 on 2022-03-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_user_address_remove_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='step',
            field=models.IntegerField(default=-1),
        ),
    ]
